### ISSUE TITLE
Suggestion: Automatization for elemental armor types

### ISSUE THREAD

**Issue by Ghostwalker83** [JDCalvert/pf2e-kineticists-companion#1]
The elemental armor effects, such as Armor in Earth, Hardwood Armor and Metal Carapace are a bit of a pain to use. For Hardwood Armor and Metal Carapace, I currently create separate armor items with the respective stats, but Armor in Earth requires a custom effect, as the armor type is actually relevant. I found someone online who created a custom effect for this which he provided (attached), but it would be really neat to have this in a module. My own coding capacities are however far from sufficient to do this.

[fvtt-Item-effect_-armor-in-earth-VvvXKVd4Oa0sRvp3.json](https://github.com/user-attachments/files/17555542/fvtt-Item-effect_-armor-in-earth-VvvXKVd4Oa0sRvp3.json)

**Comment by JDCalvert** [comment]
I've added automation for these impulses to release 1.2.0. Please let me know if they do the job!

**Comment by Ghostwalker83** [comment]
Works great, thanks a lot!
