### ISSUE TITLE
Kineticist Companion: Fresh Produce automation error

### ISSUE THREAD

**Issue by ml6k** [JDCalvert/pf2e-kineticists-companion#11]
Love the work you've been doing on the Kineticist Companion module! However, I'm coming to you with an error in hopes of a solution. I've noticed that when a kineticist with Fresh Produce uses the automation, it will sometimes report incorrect static healing that does not match the description. See below, a screenshot of the kineticist using it once for 1d4+1, and once for 1d4+6 even though both descriptions and the text from Rage of Elements read 1d4+1.

![tfdhf](https://github.com/user-attachments/assets/0fb34708-980f-4d68-b348-686d69679642)

However, I've identified the problem. The only difference in those two messages was that the first one was done at level 1, and then the second one was done at level 2. Noticing this, I checked every level, and found that Fresh Produce automation erroneously granted 5 more static healing than intended at every even level. See below for a list of the intended effects at each level, under column "RAW", and the results I was able to consistently reproduce using the Fresh Produce automation, under column "KC"

![thdesftj](https://github.com/user-attachments/assets/36e7baa1-54ed-4b67-aea0-ae8226abe670)

I hope this helps. My kineticist player and I are both really excited to see this module's growth!

**Comment by JDCalvert** [comment]
Woops! Thanks for the report, I'll get that sorted later today.

**Comment by JDCalvert** [comment]
Fixed in [1.6.1](https://github.com/JDCalvert/pf2e-kineticists-companion/releases/tag/1.6.1).
