### ISSUE TITLE
Suggestion: Automate the cooldown on Ocean's Balm and Torrent in the Blood

### ISSUE THREAD

**Issue by ConnorJBeck** [JDCalvert/pf2e-kineticists-companion#2]
Not sure if it's possible, but it'd be very neat and handy. 

Ocean's Balm (https://2e.aonprd.com/Feats.aspx?ID=4267) and Torrent in the Blood (https://2e.aonprd.com/Feats.aspx?ID=4273) both have immunity periods that last 10 minutes. It'd be nice if there could be some automation for this: Ideally, it would both automatically apply the immunity when the healing is applied and prevent further healing from being applied (or the ability from being used) if the target is currently immune. 

I've currently just added an effect in the description I can drag onto someone, but it's not very automated, it doesn't prevent the ability from accidentally being cast on someone within the immunity period, and the additional effect gets removed from the description every time I refresh from the compendium.

Loving the other parts of this btw! I have 2 kineticists in my party (Fire, Water/Metal) and so Thermal Nimbus and Metal Carapace automation is such a godsend.

**Comment by JDCalvert** [comment]
Added in [1.5.0](https://github.com/JDCalvert/pf2e-kineticists-companion/releases/tag/1.5.0).
