### ISSUE TITLE
Suggestion: Setting-Option to make Thermal Nimbus Damage not auto apply

### ISSUE THREAD

**Issue by Neakas** [JDCalvert/pf2e-kineticists-companion#3]
Hi!

Great Module! My Kineticist will be stocked. The only thing i do not like as much is the Auto-Application of Damage to Enemies.
Would be Great if you could implement a Toggle Button in the Settings of the Module, that lets me choose. So if Auto-Application was toogled off, it should create a Damage Chat Card for the Enemies in Range, that i could apply manually.

thanks for the consideration!

**Comment by JDCalvert** [comment]
Added in 1.3.1
