### ISSUE TITLE
Protector Tree Grants Flanking

### ISSUE THREAD

**Issue by 7H3LaughingMan** [JDCalvert/pf2e-kineticists-companion#4]
It looks like the Protector Tree that you summon via Timber Sentinel is granting flanking when it shouldn't. You will probably need to wrap canAttack and return false for any Protector Trees.

https://github.com/foundryvtt/pf2e/blob/8edba73196195f1bc2f59be97e5c0ad914ee430c/src/module/actor/creature/document.ts#L147

**Comment by JDCalvert** [comment]
Fixed in 1.3.1. Note that I've changed how the Protector Tree actor works entirely, so all protector trees must be replaced.
