### ISSUE TITLE
Set Custom Timber Sentinel Images

### ISSUE THREAD

**Issue by RisingStarPF2e** [JDCalvert/pf2e-kineticists-companion#5]
Every party I have ever seen a Timber Sentinel user, usually somebody in the party or etc likes it when the tree is something adorable or ridiculous.

- Right now when you use the PF2e Kineticists Companion automation it will default the prototype token image. Regardless of what you set the actor entity or etc.
- Fix: A setting in the module to point towards a image location for the token OR maybe there's a way to get it to respect the set images?

![image](https://github.com/user-attachments/assets/12dea60d-09aa-445b-9c86-307988536682)

**Comment by JDCalvert** [comment]
Spawned Protector Trees should now respect the image and bar display settings in the world actor's prototype token settings, as of 1.3.1.

**Comment by RisingStarPF2e** [comment]
**We love you JD and we SPEAKETH THY NAME!**
